import { client } from "..";

client
  .getBacklinks({
    target: "apple.com",
    target_type: "domain", // Optional, default is "domain"
    display_limit: 5, // Optional, default is 1000
  })
  .then((data) => {
    console.log(data);
  });

// [
//   {
//     page_ascore: "88",
//     response_code: "200",
//     source_size: "113818",
//     external_num: "13",
//     internal_num: "57",
//     redirect_url: "",
//     source_url:
//       "https://www.apple.com.cn/legal/internet-services/terms/site.html",
//     source_title: "Legal - Website Terms of Use - Apple",
//     image_url: "",
//     target_url: "https://apple.com/legal/contact/#copyright-infringement",
//     target_title: "",
//     anchor: "版权侵权损害赔偿请求",
//     image_alt: "",
//     last_seen: "1752366883",
//     first_seen: "1736875548",
//     nofollow: "false",
//     form: "false",
//     frame: "false",
//     image: "false",
//     sitewide: "false",
//     newlink: "false",
//     lostlink: "false",
//   },
//   {
//     page_ascore: "88",
//     response_code: "200",
//     source_size: "113818",
//     external_num: "13",
//     internal_num: "57",
//     redirect_url: "",
//     source_url:
//       "https://www.apple.com.cn/legal/internet-services/terms/site.html",
//     source_title: "Legal - Website Terms of Use - Apple",
//     image_url: "",
//     target_url: "https://apple.com/legal/contact/#counterfeit",
//     target_title: "",
//     anchor: "假冒产品",
//     image_alt: "",
//     last_seen: "1752366883",
//     first_seen: "1732165945",
//     nofollow: "false",
//     form: "false",
//     frame: "false",
//     image: "false",
//     sitewide: "false",
//     newlink: "false",
//     lostlink: "false",
//   },
//   {
//     page_ascore: "88",
//     response_code: "200",
//     source_size: "113818",
//     external_num: "13",
//     internal_num: "57",
//     redirect_url: "",
//     source_url:
//       "https://www.apple.com.cn/legal/internet-services/terms/site.html",
//     source_title: "Legal - Website Terms of Use - Apple",
//     image_url: "",
//     target_url: "https://apple.com/legal/contact/",
//     target_title: "",
//     anchor: "法务联系人",
//     image_alt: "",
//     last_seen: "1752366883",
//     first_seen: "1727670830",
//     nofollow: "false",
//     form: "false",
//     frame: "false",
//     image: "false",
//     sitewide: "false",
//     newlink: "false",
//     lostlink: "false",
//   },
//   {
//     page_ascore: "87",
//     response_code: "200",
//     source_size: "153891",
//     external_num: "8",
//     internal_num: "63",
//     redirect_url: "",
//     source_url: "https://www.apple.com.cn/shop/browse/open/salespolicies",
//     source_title: "销售和退款政策 - Apple (中国大陆)",
//     image_url: "",
//     target_url:
//       "http://apple.com/legal/warranty/products/ios-warranty-china.html",
//     target_title: "",
//     anchor:
//       "http://www.apple.com/legal/warranty/products/ios-warranty-china.html",
//     image_alt: "",
//     last_seen: "1752832317",
//     first_seen: "1735157153",
//     nofollow: "false",
//     form: "false",
//     frame: "false",
//     image: "false",
//     sitewide: "false",
//     newlink: "false",
//     lostlink: "false",
//   },
//   {
//     page_ascore: "84",
//     response_code: "200",
//     source_size: "635955",
//     external_num: "32",
//     internal_num: "121",
//     redirect_url: "",
//     source_url: "https://coolors.co/",
//     source_title: "Coolors - The super fast color palettes generator!",
//     image_url: "",
//     target_url: "https://apple.com/",
//     target_title: "",
//     anchor: "",
//     image_alt: "",
//     last_seen: "1753022457",
//     first_seen: "1735163130",
//     nofollow: "false",
//     form: "false",
//     frame: "false",
//     image: "false",
//     sitewide: "false",
//     newlink: "false",
//     lostlink: "false",
//   },
// ];
