import { client } from "..";

client
  .getUrlOrganicSearchKeywords({
    url: "https://developer.semrush.com/api/v3/analytics/url-reports/",
    display_limit: 4,
  })
  .then((data) => {
    console.log(data);
  });
//   [
//     {
//       keyword: 'url reports',
//       position: '12',
//       previous_position: '12',
//       search_volume: '40',
//       cpc: '0.00',
//       competition: '0.09',
//       keyword_difficulty: '66.00',
//       'traffic_(%)': '0.00',
//       traffic: '0',
//       'traffic_cost_(%)': '0.00',
//       number_of_results: '1510000000',
//       trends: '0.28,0.14,0.28,1.00,0.14,0.14,0.50,0.14,0.50,0.14,0.14,0.14',
//       serp_features_by_position: '',
//       serp_features_by_keyword: '9,21,36,52',
//       timestamp: '1753785000',
//       intents: '1',
//       position_type: 'Organic'
//     },
//     {
//       keyword: 'ebay email checker semrush',
//       position: '10',
//       previous_position: '10',
//       search_volume: '70',
//       cpc: '0.00',
//       competition: '0.00',
//       keyword_difficulty: '49.00',
//       'traffic_(%)': '0.00',
//       traffic: '0',
//       'traffic_cost_(%)': '0.00',
//       number_of_results: '46',
//       trends: '0.45,1.00,0.81',
//       serp_features_by_position: '',
//       serp_features_by_keyword: '5,9,36',
//       timestamp: '1756018136',
//       intents: '1',
//       position_type: 'Organic'
//     },
//     {
//       keyword: 'download email checker semrush',
//       position: '73',
//       previous_position: '73',
//       search_volume: '70',
//       cpc: '0.00',
//       competition: '0.00',
//       keyword_difficulty: '43.00',
//       'traffic_(%)': '0.00',
//       traffic: '0',
//       'traffic_cost_(%)': '0.00',
//       number_of_results: '134000',
//       trends: '0.27,0.81,1.00',
//       serp_features_by_position: '',
//       serp_features_by_keyword: '5,6,9,36',
//       timestamp: '1754815452',
//       intents: '2',
//       position_type: 'Organic'
//     },
//     {
//       keyword: 'google email username checker semrush',
//       position: '83',
//       previous_position: '83',
//       search_volume: '40',
//       cpc: '0.00',
//       competition: '0.00',
//       keyword_difficulty: '38.00',
//       'traffic_(%)': '0.00',
//       traffic: '0',
//       'traffic_cost_(%)': '0.00',
//       number_of_results: '3390000',
//       trends: '0.14,1.00,0.57',
//       serp_features_by_position: '',
//       serp_features_by_keyword: '6,9,36',
//       timestamp: '1755550632',
//       intents: '1',
//       position_type: 'Organic'
//     },
//     {
//       keyword: 'email address availability checker semrush',
//       position: '26',
//       previous_position: '26',
//       search_volume: '70',
//       cpc: '0.00',
//       competition: '0.00',
//       keyword_difficulty: '31.00',
//       'traffic_(%)': '0.00',
//       traffic: '0',
//       'traffic_cost_(%)': '0.00',
//       number_of_results: '1640000',
//       trends: '0.55,1.00,1.00',
//       serp_features_by_position: '',
//       serp_features_by_keyword: '9,36,52',
//       timestamp: '1756021896',
//       intents: '1',
//       position_type: 'Organic'
//     },
//     {
//       keyword: 'check email addresses semrush',
//       position: '70',
//       previous_position: '70',
//       search_volume: '70',
//       cpc: '0.00',
//       competition: '0.00',
//       keyword_difficulty: '33.00',
//       'traffic_(%)': '0.00',
//       traffic: '0',
//       'traffic_cost_(%)': '0.00',
//       number_of_results: '207000',
//       trends: '0.57,1.00',
//       serp_features_by_position: '',
//       serp_features_by_keyword: '5,9,11,21,36',
//       timestamp: '1753606309',
//       intents: '1',
//       position_type: 'Organic'
//     }
